name: Check docker build
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  Whisperer_Unit_Testing:
    runs-on: [ubuntu-latest]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: whisperer:latest

